// Generated by ReScript, PLEASE EDIT WITH CARE


let screenWidth = 160.0 * 6.0;

let screenHeight = 120.0 * 6.0;

let bgColor = "#fff";

let textColor = "#000";

function main() {
  window.setup = () => {
    createCanvas(screenWidth, screenHeight);
    background(bgColor);
    fill(textColor);
    textFont("monospace");
    textSize(6.0 * 4.0);
    text("Exercise 0.4 (ReScript + p5.js)", 2.0 * 6.0, 6.0 * 6.0);
  };
  window.draw = () => {
    let x = randomGaussian(screenWidth / 2.0, 150.0);
    let y = randomGaussian(screenHeight / 2.0, 130.0);
    let r = random(255);
    let g = random(255);
    let b = random(255);
    let a = random(255);
    let circleSize = random([
      16,
      30
    ]);
    noStroke();
    fill([
      r,
      g,
      b,
      a
    ]);
    circle(x, y, circleSize);
  };
  new p5();
}

main();

let baseWidth = 160.0;

let baseHeight = 120.0;

let scaleFactor = 6.0;

export {
  baseWidth,
  baseHeight,
  scaleFactor,
  screenWidth,
  screenHeight,
  bgColor,
  textColor,
  main,
}
/*  Not a pure module */
